name: gcse-pal
services:
- name: platform
  source_dir: /apps/platform
  github:
    repo: naurunnahansa/gcse-pal
    branch: main
  run_command: cd apps/platform && npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  build_command: cd apps/platform && npx prisma generate && npm run build
  environment:
  - name: NODE_ENV
    value: production
  - name: DATABASE_URL
    value: ${DATABASE_URL}
  - name: OPENROUTER_API_KEY
    value: ${OPENROUTER_API_KEY}
  - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    value: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
  - name: CLERK_SECRET_KEY
    value: ${CLERK_SECRET_KEY}